### ISSUE TITLE
Autoresize not working with Retropie 4.4 image

### ISSUE THREAD

**Issue by ziggymaj** [Drewsif/PiShrink#62] opened 2018-05-02 18:14 UTC
Autoresize not working with Retropie 4.4 image

**Comment by framps** [comment] 2018-05-03 18:13
@ziggymaj `Does not work` doesn't help to find the root cause for the issue. Please describe the issue in more detail. For example create a detailed error report of the following way:
1. Invoke `script` in a commandline window
2. Invoke pishrink 
3. Type `exit`
4. Post the contents of file `typescript`

**Comment by FuriousMidgett** [comment] 2018-12-01 19:14
I have the same issue. No error is present. Image shrinks properly. Unshrunk image copies perfectly. Retropie 4.3 images shrink and play fine.

The issue seems to be based on the image getting hung up on first boot when trying to automatically resize on Retropie 4.4 (Stretch).

**Comment by Drewsif** [comment] 2020-06-17 20:01
This is a duplicate issue of the parted problem some people were seeing. Closing this one as a duplicate

**Closed by Drewsif** 2020-06-17 20:01 UTC
