### ISSUE TITLE
[Feature Request] Add an output option

### ISSUE THREAD

**Issue by Septolum** [Drewsif/PiShrink#2] opened 2016-04-26 16:26 UTC
Add an output option to write the new smaller file to a different file

**Comment by Drewsif** [comment] 2016-04-27 04:14
Duplicate of #1. Closing this one

**Closed by Drewsif** 2016-04-27 04:14 UTC

**Comment by Septolum** [comment] 2016-04-27 05:46
This isn't a duplicate of #1, issue 1 is a request for a mode where nothing is written, in a similar style to apt-get's -s s"imulate" option

**Comment by Drewsif** [comment] 2016-04-27 20:03
My mistake, I misread #1 and thought it included that idea.

While I do think this is a great idea, I don't know if it can be done since I rely on resize2fs and it has no option to write to a different device. There is no good way to preserver the original image without making a straight copy of it that I can see.
