### ISSUE TITLE
Using PiShrink with resized partition

### ISSUE THREAD

**Issue by bizzar721** [Drewsif/PiShrink#76] opened 2018-09-15 15:30 UTC
Drewsif  Awesome utility you have made!   I am wondering if it is possible to pishrink an image using a resized partition which was created using the command `tune2fs -m .5 /dev/mmcblk0p2` which reclaims the space that Raspian reserves from 5%  down to only 0.5% (that .5 could be changed to whichever suits your need - .5 leaves just over 500Mb reserved on a 128Gb SD card which should be more than enough if the need should arise) 
It wouldn't shrink with autoexpand enabled - without autoexpand enabled it would shrink but the image wouldn't boot.  I cannot remember the errors I recieved.  Is there a solution to make this work?
Thank you.

**Comment by Drewsif** [comment] 2018-10-30 17:04
The only reason I can think it would break is if it shrinks too much there wont be free space to boot? But I think it should work, what was the error you were getting?

**Comment by bizzar721** [comment] 2018-10-31 03:09
I created another backup of my expanded build (Retropie 4.4 Stretch) so I can test.  When run with command `sudo ./pishrink.sh expandedbackup.img`  I get 
`Creating new /etc/rc.local
retropie: 536767/7488992 files (0.3% non-contiguous), 30344081/30704384 blocks
resize2fs 1.42.13 (17-May-2015)
ERROR: Image already shrunk to smallest size
`

**Comment by Drewsif** [comment] 2020-06-17 19:54
You're not the first one to report this issue, it's on my todo list so I'm going to close this issue as a duplicate of #80

**Closed by Drewsif** 2020-06-17 19:54 UTC
