### ISSUE TITLE
Creating sprase image before compressing

### ISSUE THREAD

**Issue by dilyanpalauzov** [Drewsif/PiShrink#187] opened 2021-02-08 10:22 UTC
In order to get smaller compressed image, place allocated by deleted files shall be zeroed.  This is called “sparse image”.  According to https://ext4.wiki.kernel.org/index.php/Ext4_VM_Images#Good_Tools_for_Making_Sparse_Images:_fstrim.2Fe2fsck.2Fzerofree to create a sparse image one has to call `e2fsck -E discard $loopback`.

• Call `e2fsck -E discard $loopback` on the resulting image.

**Comment by jfikar** [comment] 2021-02-27 16:29
The command `e2fsck -E discard $device` does not seem to discard the free space. Even `e2fsck -f -y -D -E discard $device` does not work.

On contrary, the `zerofree` of `dd if=/dev/zero of=zerofile;sync;sync;rm zerofile` works just fine.

There is also a possibility to create a sparse file at the end, if you are not compressing it by `fallocate -d image`

**Comment by Drewsif** [comment] 2023-02-14 06:34
Duplicate of #59

**Closed by Drewsif** 2023-02-14 06:34 UTC
